[package]
name = "pallet-schemas-rpc"
version = "0.1.0"
description = "RPC package for schemas"
authors = ["Frequency Team"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/libertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }

# unfinished
pallet-schemas-runtime-api = { path = "../runtime-api", default-features = false }
common-primitives = { path = '../../../../common/primitives', default-features = false }
common-helpers = { path = '../../../../common/helpers', default-features = false }

# Substrate
frame-support = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-core = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"  }
sp-rpc = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"  }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"  }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"  }
sp-std = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"pallet-schemas-runtime-api/std",
	"common-primitives/std",
]
