[package]
name = "pallet-schemas-runtime-api"
version = "0.1.0"
description = "RPC runtime package for schemas"
authors = ["Frequency Team"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/libertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

# Substrate
sp-runtime = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-std = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }

# Frequency related dependencies
common-primitives = { default-features = false, path = "../../../../common/primitives" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"frame-support/std",
	"common-primitives/std",
	"sp-std/std",
]
