[package]
name = "pallet-schemas"
authors = ["Frequency Team"]
description = "Schema operations"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
publish = false
repository = "https://github.com/libertyDSNP/frequency/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
]}
smallvec = "1.7.0"
frame-benchmarking = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b", optional = true}
frame-support = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
frame-system = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
scale-info = {version = "2.0.0", default-features = false, features = ["derive"]}
sp-io = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
sp-runtime = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
sp-std = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
sp-core = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
numtoa = { default-features = false, version = '0.2.4', optional = true}

# Frequency related dependencies
common-primitives = {default-features = false, path = "../../common/primitives"}

[dev-dependencies]
sp-keyring = { default-features = false, version = '6.0.0'}
serial_test = { default-features = false, version = '0.8.0' }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-core/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"numtoa"
]

try-runtime = ["frame-support/try-runtime"]
