[package]
name = "pallet-msa-rpc"
version = '0.1.0'
description = 'A package that adds RPC to Msa pallet'
authors = ['Frequency Team']
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }
rayon = "1.5"

# unfinished
pallet-msa-runtime-api = {default-features = false, path = "../runtime-api" }
common-primitives = {default-features = false, path = "../../../../common/primitives" }
common-helpers = {default-features = false, path = "../../../../common/helpers" }

# Substrate packages
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }

[features]
default = ["std"]
std = [
	'codec/std',
	"sp-api/std",
	"sp-runtime/std",
	"pallet-msa-runtime-api/std",
	'common-primitives/std',
]
