[package]
authors = ["Frequency Team"]
description = "A package that defines common primitives used in runtime and RPCs"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = 'common-primitives'
publish = false
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"]}
impl-serde = {version = "0.3.1", default-features = false}
scale-info = {version = "2.0.1", default-features = false, features = ["derive"]}
serde = { version = "1.0", default-features = false, features = ["derive"] }

frame-support = {default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
smallvec = "1.7.0"
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b" }

[features]
default = ['std']
std = [
  'codec/std',
  'frame-support/std',
  'sp-std/std',
  'sp-runtime/std',
  'sp-api/std',
]
