[package]
name = "frequency-node"
version = "0.1.0"
authors = ["Frequency Team"]
description = "Substrate node for frequency"
license = "Apache-2.0"
homepage = "https://frequency.xyz/"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"

[[bin]]
name = "frequency-collator"
path = "src/main.rs"

#Frequency Cli
[dependencies]
futures = { version = "0.3.1", features = [ "compat" ] }
frequency-cli = { path = "cli", default-features = false }
frequency-service = { path = "service", default-features = false }

# Frequency Runtime
frequency-runtime = { path = "../runtime/frequency" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }

[features]
runtime-benchmarks = [
	"frequency-runtime/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
]
try-runtime = ["frequency-runtime/try-runtime"]
