[package]
authors = ["Frequency Team"]
build = "build.rs"
description = "Substrate node for Frequency"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "frequency"
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.1.0"

[[bin]]
name = "frequency"
path = "src/main.rs"

[dependencies]
# Frequency Runtime
frequency-cli = {path = "cli"}
frequency-rococo-runtime = {path = "../runtime/frequency-rococo"}
frequency-runtime = {path = "../runtime/frequency"}
zstd = "0.11"


# Substrate
sc-cli = {git = "https://github.com/paritytech/substrate", features = ["wasmtime"], rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}

[features]
runtime-benchmarks = [
  "frequency-runtime/runtime-benchmarks",
  "frequency-rococo-runtime/runtime-benchmarks",
  "frequency-cli/runtime-benchmarks",
]
try-runtime = ["frequency-runtime/try-runtime", "frequency-rococo-runtime/try-runtime"]
