[package]
authors = ["Frequency Team"]
description = "Substrate cli for frequency node"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = "frequency-cli"
repository = "https://github.com/LibertyDSNP/frequency/"
version = "0.1.0"

[dependencies]
clap = {version = "3.2.5", features = ["derive"]}
codec = {package = "parity-scale-codec", version = "3.0.0"}
derive_more = "0.99.2"
hex-literal = "0.3.4"
jsonrpsee = {version = "0.14.0", features = ["server"]}
log = "0.4.17"
serde = {version = "1.0.137", features = ["derive"]}

# Frequency Runtime
common-primitives = {default-features = false, path = "../../common/primitives"}
frequency-rococo-runtime = {path = "../../runtime/frequency-rococo"}
frequency-runtime = {path = "../../runtime/frequency"}
frequency-service = {package = "frequency-service", path = "../service", default-features = false, optional = true}

# Substrate
frame-benchmarking-cli = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b", optional = true}
sc-cli = {git = "https://github.com/paritytech/substrate", features = ["wasmtime"], rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b", optional = true}
sc-service = {git = "https://github.com/paritytech/substrate", features = ["wasmtime"], rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b", optional = true}
sc-sysinfo = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
sc-telemetry = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
sc-tracing = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
sp-core = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b", optional = true}
sp-runtime = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}
try-runtime-cli = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b", optional = true}

# Polkadot
polkadot-cli = {git = "https://github.com/paritytech/polkadot", rev = "d8785970175dce344f2a6ad1cd88297529a6dd59"}
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", rev = "d8785970175dce344f2a6ad1cd88297529a6dd59"}
polkadot-primitives = {git = "https://github.com/paritytech/polkadot", rev = "d8785970175dce344f2a6ad1cd88297529a6dd59"}
polkadot-service = {git = "https://github.com/paritytech/polkadot", rev = "d8785970175dce344f2a6ad1cd88297529a6dd59"}

# Cumulus
cumulus-client-cli = {git = "https://github.com/paritytech/cumulus", rev = "e43b8b878a6fd0ca8b5e88d19822c4d777d3c677"}
cumulus-client-service = {git = "https://github.com/paritytech/cumulus", rev = "e43b8b878a6fd0ca8b5e88d19822c4d777d3c677"}
cumulus-primitives-core = {git = "https://github.com/paritytech/cumulus", rev = "e43b8b878a6fd0ca8b5e88d19822c4d777d3c677"}

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/substrate", rev = "e8a7d161f39db70cb27fdad6c6e215cf493ebc3b"}

[features]
cli = [
  "frequency-service",
  "sp-core",
  "sc-cli",
  "sc-service",
  "frame-benchmarking-cli",
  "try-runtime-cli",
]
default = ["wasmtime", "cli"]
runtime-benchmarks = [
  "polkadot-cli/runtime-benchmarks",
]
try-runtime = []
wasmtime = ["sc-cli/wasmtime"]
